apiVersion: v1
data:
  InterLinkConfig.yaml: |
    InterlinkURL: https://{{.InterLinkIP}}
    InterlinkPort: {{.InterLinkPort}}
    CommandPrefix: ""
    ExportPodData: true
    ServiceAccount: "interlink"
    Namespace: {{.Namespace}}
    VKTokenFile: /opt/interlink/token
    CPU: "{{.VKLimits.CPU}}"
    Memory: "{{.VKLimits.Memory}}",
    Pods: "{{.VKLimits.Pods}}"
kind: ConfigMap
metadata:
  name: "{{.VKName}}-config"
  namespace: {{.Namespace}} 
