apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.nodeName }}
  namespace: {{ .Release.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "{{ .Values.nodeName }}-role"
  namespace: {{ .Release.namespace }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  - services
  - serviceaccounts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - delete
  - get
  - list
  - watch
  - patch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - create
  - get
- apiGroups:
  - ""
  resources:
  - nodes/status
  verbs:
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - pods/status
  verbs:
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "{{ .Values.nodeName }}-rolebinding"
subjects:
- kind: ServiceAccount
  name: {{ .Values.nodeName }}
  namespace: {{ .Release.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "{{ .Values.nodeName }}-role"
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.nodeName }}-secret"
  namespace: "{{ .Release.namespace }}"
  annotations:
    kubernetes.io/service-account.name: {{ .Values.nodeName }}
  labels:
    kubernetes.io/service-account.name: {{ .Values.nodeName }}
type: kubernetes.io/service-account-token
