apiVersion: v1
kind: ConfigMap
metadata:
  name: "virtual-kubelet-config"
  namespace: {{ .Release.Namespace }}
data:
  InterLinkConfig.yaml: |
    InterlinkURL: {{ .Values.interlink.URL }}
    InterlinkPort: {{ .Values.interlink.port }}
    ExportPodData: true
    VerboseLogging: true
    ErrorsOnlyLogging: false
    ServiceAccount: "{{ .Values.nodeName }}"
    Namespace: ""
    VKTokenFile: /opt/interlink/token 
    CPU: "{{ .Values.virtualNode.CPUs }}"
    Memory: "{{ .Values.virtualNode.MemGiB }}GiB"
    Pods: "{{ .Values.virtualNode.Pods }}"
