#!/bin/bash

# interLink Remote Installation Script
# Generated by interLink WebUI

set -e

INTERLINK_VERSION="{{.InterLinkVersion}}"
INTERLINK_PORT="{{.InterLinkPort}}"
INTERLINK_IP="{{.InterLinkIP}}"

install() {
    echo "Installing interLink API Server version $INTERLINK_VERSION..."
    
    # Download interLink binary
    curl -Lo interlink "https://github.com/interlink-hq/interlink/releases/download/v$INTERLINK_VERSION/interlink-linux-amd64"
    chmod +x interlink
    sudo mv interlink /usr/local/bin/
    
    # Create configuration directory
    sudo mkdir -p /etc/interlink
    
    # Create interLink configuration
    cat > /tmp/interLinkConfig.yaml << 'EOF'
InterlinkAddress: "0.0.0.0"
InterlinkPort: {{.InterLinkPort}}
SidecarURL: "http://localhost:4000"
SidecarEndpoint: "http://localhost:4000"
VerboseLogging: true
ErrorsOnlyLogging: false
ExportPodData: true
DataRootFolder: "/tmp/interlink"
{{- if .OAUTH.ClientID}}
Oauth:
  Provider: "{{.OAUTH.Provider}}"
  Issuer: "{{.OAUTH.Issuer}}"
  Audience: "{{.OAUTH.Audience}}"
  ClientId: "{{.OAUTH.ClientID}}"
  ClientSecret: "{{.OAUTH.ClientSecret}}"
  GroupClaim: "{{.OAUTH.GroupClaim}}"
  {{- if .OAUTH.Group}}
  Group: "{{.OAUTH.Group}}"
  {{- end}}
{{- end}}
EOF
    
    sudo mv /tmp/interLinkConfig.yaml /etc/interlink/
    
    # Create systemd service
    cat > /tmp/interlink.service << 'EOF'
[Unit]
Description=interLink API Server
After=network.target

[Service]
Type=simple
User=root
ExecStart=/usr/local/bin/interlink --config /etc/interlink/interLinkConfig.yaml
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
EOF
    
    sudo mv /tmp/interlink.service /etc/systemd/system/
    sudo systemctl daemon-reload
    sudo systemctl enable interlink
    
    echo "interLink installed successfully!"
    
    # Plugin setup
    setup_plugin
    
    echo ""
    echo "🚀 Installation Complete!"
    echo "Next steps:"
    echo "1. Deploy Virtual Kubelet using the generated Helm values"
    echo "2. Test the deployment with: kubectl get nodes"
}

setup_plugin() {
    echo ""
    echo "🔌 Setting up {{if .Plugin}}{{.Plugin}}{{else}}docker{{end}} plugin..."
    
    {{- if eq .Plugin "docker"}}
    # Docker plugin setup
    echo "Installing Docker plugin..."
    
    # Check if Docker is installed
    if ! command -v docker &> /dev/null; then
        echo "⚠️  Docker not found. Installing Docker..."
        # Install Docker (Ubuntu/Debian)
        sudo apt-get update
        sudo apt-get install -y docker.io jq
        sudo systemctl start docker
        sudo systemctl enable docker
        sudo usermod -aG docker $USER
        echo "✅ Docker installed successfully"
    else
        echo "✅ Docker already installed"
    fi
    
    # Create directories
    sudo mkdir -p /opt/interlink/bin /opt/interlink/config /opt/interlink/logs /opt/interlink/jobs
    sudo chown -R root:root /opt/interlink
    sudo chmod 755 /opt/interlink/bin /opt/interlink/config
    sudo chmod 755 /opt/interlink/logs /opt/interlink/jobs
    
    # Download Docker plugin binary
    echo "Downloading Docker plugin binary..."
    PLUGIN_VERSION=$(curl -s https://api.github.com/repos/interlink-hq/interlink-docker-plugin/releases/latest | jq -r .name)
    sudo curl -L -o /opt/interlink/bin/plugin \
        "https://github.com/interlink-hq/interlink-docker-plugin/releases/download/${PLUGIN_VERSION}/interlink-sidecar-docker_Linux_x86_64"
    sudo chmod +x /opt/interlink/bin/plugin
    
    # Create Docker plugin configuration
    cat > /tmp/plugin-config.yaml << 'EOF'
Socket: "tcp://0.0.0.0:4000"
InterlinkPort: "0"
SidecarPort: "4000"
CommandPrefix: ""
DataRootFolder: "/opt/interlink/jobs/"
BashPath: /bin/bash
VerboseLogging: false
ErrorsOnlyLogging: false
EOF
    sudo mv /tmp/plugin-config.yaml /opt/interlink/config/
    
    # Create systemd service for Docker plugin
    cat > /tmp/interlink-docker-plugin.service << 'EOF'
[Unit]
Description=InterLink Docker Plugin
After=network.target docker.service
Wants=network.target
Requires=docker.service

[Service]
Type=simple
User=root
Group=root
WorkingDirectory=/opt/interlink
Environment=INTERLINKCONFIGPATH=/opt/interlink/config/plugin-config.yaml
ExecStart=/opt/interlink/bin/plugin
ExecReload=/bin/kill -HUP $MAINPID
Restart=always
RestartSec=10
StandardOutput=append:/opt/interlink/logs/plugin.log
StandardError=append:/opt/interlink/logs/plugin.log

[Install]
WantedBy=multi-user.target
EOF
    sudo mv /tmp/interlink-docker-plugin.service /etc/systemd/system/
    sudo systemctl daemon-reload
    sudo systemctl enable interlink-docker-plugin
    sudo systemctl start interlink-docker-plugin
    
    # Wait for plugin to be ready
    echo "Waiting for Docker plugin to be ready..."
    for i in {1..30}; do
        if curl -s http://localhost:4000/status &>/dev/null; then
            echo "✅ Docker plugin is ready!"
            break
        fi
        sleep 2
    done
    
    {{- else if eq .Plugin "slurm"}}
    # SLURM plugin setup
    echo "Installing SLURM plugin..."
    
    # Check if SLURM client tools are installed
    if ! command -v sbatch &> /dev/null || ! command -v squeue &> /dev/null || ! command -v scancel &> /dev/null; then
        echo "⚠️  SLURM client tools not found. Installing..."
        # Install SLURM client (Ubuntu/Debian)
        sudo apt-get update
        sudo apt-get install -y slurm-client
        echo "✅ SLURM client tools installed"
    else
        echo "✅ SLURM client tools already installed"
    fi
    
    # Check if Apptainer/Singularity is installed
    if ! command -v apptainer &> /dev/null && ! command -v singularity &> /dev/null; then
        echo "⚠️  Apptainer/Singularity not found. Installing Apptainer..."
        # Install Apptainer (Ubuntu/Debian)
        sudo apt-get update
        sudo apt-get install -y software-properties-common
        sudo add-apt-repository -y ppa:apptainer/ppa
        sudo apt-get update
        sudo apt-get install -y apptainer
        echo "✅ Apptainer installed successfully"
    else
        echo "✅ Container runtime (Apptainer/Singularity) already available"
    fi
    
    # Create directories
    sudo mkdir -p /opt/interlink/bin /opt/interlink/config /opt/interlink/logs /opt/interlink/jobs
    sudo chown -R root:root /opt/interlink
    sudo chmod 755 /opt/interlink/bin /opt/interlink/config
    sudo chmod 755 /opt/interlink/logs /opt/interlink/jobs
    
    # Download SLURM plugin binary
    echo "Downloading SLURM plugin binary..."
    PLUGIN_VERSION=$(curl -s https://api.github.com/repos/interlink-hq/interlink-slurm-plugin/releases/latest | jq -r .name)
    sudo curl -L -o /opt/interlink/bin/plugin \
        "https://github.com/interlink-hq/interlink-slurm-plugin/releases/download/${PLUGIN_VERSION}/interlink-sidecar-slurm_Linux_x86_64"
    sudo chmod +x /opt/interlink/bin/plugin
    
    # Create SLURM plugin configuration
    cat > /tmp/plugin-config.yaml << 'EOF'
Socket: "tcp://0.0.0.0:4000"
InterlinkPort: "0"
SidecarPort: "4000"
CommandPrefix: ""
DataRootFolder: "/opt/interlink/jobs/"
BashPath: /bin/bash
VerboseLogging: false
ErrorsOnlyLogging: false
SbatchPath: "/usr/bin/sbatch"
ScancelPath: "/usr/bin/scancel"
SqueuePath: "/usr/bin/squeue"
SingularityPrefix: ""
EOF
    sudo mv /tmp/plugin-config.yaml /opt/interlink/config/
    
    # Create systemd service for SLURM plugin
    cat > /tmp/interlink-slurm-plugin.service << 'EOF'
[Unit]
Description=InterLink SLURM Plugin
After=network.target
Wants=network.target

[Service]
Type=simple
User=root
Group=root
WorkingDirectory=/opt/interlink
Environment=SLURMCONFIGPATH=/opt/interlink/config/plugin-config.yaml
ExecStart=/opt/interlink/bin/plugin
ExecReload=/bin/kill -HUP $MAINPID
Restart=always
RestartSec=10
StandardOutput=append:/opt/interlink/logs/plugin.log
StandardError=append:/opt/interlink/logs/plugin.log

[Install]
WantedBy=multi-user.target
EOF
    sudo mv /tmp/interlink-slurm-plugin.service /etc/systemd/system/
    sudo systemctl daemon-reload
    sudo systemctl enable interlink-slurm-plugin
    sudo systemctl start interlink-slurm-plugin
    
    # Wait for plugin to be ready
    echo "Waiting for SLURM plugin to be ready..."
    for i in {1..30}; do
        if curl -s http://localhost:4000/status &>/dev/null; then
            echo "✅ SLURM plugin is ready!"
            break
        fi
        sleep 2
    done
    
    {{- else}}
    # Generic plugin setup
    echo "Setting up {{.Plugin}} plugin..."
    echo "⚠️  Please configure your plugin manually according to its documentation"
    echo "The plugin should listen on port 4000"
    {{- end}}
    
    echo "✅ Plugin setup completed!"
}

start() {
    echo "Starting interLink service..."
    sudo systemctl start interlink
    echo "interLink service started!"
    
    # Start plugin
    {{- if eq .Plugin "docker"}}
    echo "Starting Docker plugin..."
    sudo systemctl start interlink-docker-plugin || {
        echo "Plugin service not found. Running setup_plugin to create it..."
        setup_plugin
    }
    {{- else if eq .Plugin "slurm"}}
    echo "Starting SLURM plugin..."
    sudo systemctl start interlink-slurm-plugin || {
        echo "Plugin service not found. Running setup_plugin to create it..."
        setup_plugin
    }
    {{- end}}
    
    echo "Service status:"
    sudo systemctl status interlink --no-pager
    
    {{- if or (eq .Plugin "docker") (eq .Plugin "slurm")}}
    echo ""
    echo "Plugin status:"
    {{- if eq .Plugin "docker"}}
    sudo systemctl status interlink-docker-plugin --no-pager || echo "❌ Docker plugin not running"
    {{- else if eq .Plugin "slurm"}}
    sudo systemctl status interlink-slurm-plugin --no-pager || echo "❌ SLURM plugin not running"
    {{- end}}
    {{- end}}
}

stop() {
    echo "Stopping interLink service..."
    sudo systemctl stop interlink
    echo "interLink service stopped!"
    
    # Stop plugin
    {{- if eq .Plugin "docker"}}
    echo "Stopping Docker plugin..."
    sudo systemctl stop interlink-docker-plugin 2>/dev/null || echo "Docker plugin was not running"
    {{- else if eq .Plugin "slurm"}}
    echo "Stopping SLURM plugin..."
    sudo systemctl stop interlink-slurm-plugin 2>/dev/null || echo "SLURM plugin was not running"
    {{- end}}
    
    echo "✅ All services stopped!"
}

case "$1" in
    install)
        install
        ;;
    start)
        start
        ;;
    stop)
        stop
        ;;
    *)
        echo "Usage: $0 {install|start|stop}"
        exit 1
        ;;
esac

