apiVersion: v1
kind: Service
metadata:
  name: interlink
  namespace: interlink
spec:
  selector:
    app: interlink
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: interlink
  namespace: interlink
  labels:
    app: interlink
spec:
  replicas: 1
  selector:
    matchLabels:
      app: interlink
  template:
    metadata:
      labels:
        app: interlink
    spec:
      hostNetwork: true
      containers:
        - name: interlink
          image: "ghcr.io/intertwin-eu/interlink/interlink"
          imagePullPolicy: Always
          env:
            - name: CONFIGPATH
              value: "/etc/interlink/InterLinkConfig.yaml"
          volumeMounts:
            - name: config
              mountPath: /etc/interlink/InterLinkConfig.yaml
              subPath: InterLinkConfig.yaml
      volumes:
        - name: config
          configMap:
            # Provide the name of the ConfigMap you want to mount.
            name: interlink-config
