apiVersion: v1
kind: ConfigMap
metadata:
  name: "plugin-config"
  namespace: interlink 
data:
  InterLinkConfig.yaml: |
    InterlinkURL: "http://localhost"
    InterlinkPort: "3000"
    SidecarURL: "http://0.0.0.0"
    SidecarPort: "4000"
    VerboseLogging: true
    ErrorsOnlyLogging: false
    ExportPodData: true
    DataRootFolder: "~/.interlink"
