# Default values for interlink.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nodeName: default-vk

deployment:
  image: ghcr.io/intertwin-eu/virtual-kubelet-inttw:latest 
  name: default-vk

interlink:
  URL: http://localhost
  port: 5000

virtualNode:
  CPUs: 100
  MemGiB: 1600
  Pods: 100

OAUTH:
  TokenURL: DUMMY
  ClientID: DUMMY
  ClientSecret: DUMMY
  RefreshToken: DUMMY
  Audience: DUMMY

