package main

import (
	"encoding/base64"
	"fmt"
	"strings"
)

// GenerateMTLSKubernetesManifest creates a complete Kubernetes manifest with mTLS certificates
func GenerateMTLSKubernetesManifest(certs *CertificateBundle, namespace string) string {
	// Base64 encode all certificates and keys
	caCertB64 := base64.StdEncoding.EncodeToString([]byte(certs.CACert))
	caKeyB64 := base64.StdEncoding.EncodeToString([]byte(certs.CAKey))
	serverCertB64 := base64.StdEncoding.EncodeToString([]byte(certs.ServerCert))
	serverKeyB64 := base64.StdEncoding.EncodeToString([]byte(certs.ServerKey))
	clientCertB64 := base64.StdEncoding.EncodeToString([]byte(certs.ClientCert))
	clientKeyB64 := base64.StdEncoding.EncodeToString([]byte(certs.ClientKey))

	manifest := fmt.Sprintf(`---
# Namespace for interLink mTLS deployment
apiVersion: v1
kind: Namespace
metadata:
  name: %s
  labels:
    app.kubernetes.io/name: interlink
    app.kubernetes.io/component: mtls-deployment

---
# CA Certificate Secret
apiVersion: v1
kind: Secret
metadata:
  name: interlink-ca-certs
  namespace: %s
  labels:
    app.kubernetes.io/name: interlink
    app.kubernetes.io/component: certificates
    app.kubernetes.io/part-of: interlink
type: Opaque
data:
  ca.crt: %s
  ca.key: %s

---
# Server Certificate Secret for interLink API
apiVersion: v1
kind: Secret
metadata:
  name: interlink-server-certs
  namespace: %s
  labels:
    app.kubernetes.io/name: interlink
    app.kubernetes.io/component: certificates
    app.kubernetes.io/part-of: interlink
type: kubernetes.io/tls
data:
  tls.crt: %s
  tls.key: %s
  ca.crt: %s

---
# Client Certificate Secret for Virtual Kubelet
apiVersion: v1
kind: Secret
metadata:
  name: interlink-client-certs
  namespace: %s
  labels:
    app.kubernetes.io/name: interlink
    app.kubernetes.io/component: certificates
    app.kubernetes.io/part-of: interlink
type: kubernetes.io/tls
data:
  tls.crt: %s
  tls.key: %s
  ca.crt: %s

---
# ConfigMap with interLink configuration for mTLS
apiVersion: v1
kind: ConfigMap
metadata:
  name: interlink-config
  namespace: %s
  labels:
    app.kubernetes.io/name: interlink
    app.kubernetes.io/component: configuration
    app.kubernetes.io/part-of: interlink
data:
  InterLinkConfig.yaml: |
    InterlinkAddress: https://0.0.0.0
    InterlinkPort: "3000"
    SidecarURL: http://plugin
    SidecarPort: "4000"
    VerboseLogging: true
    ErrorsOnlyLogging: false
    DataRootFolder: "/tmp/interlink"
    
    # mTLS Configuration
    TLS:
      Enabled: true
      CertFile: "/etc/interlink/certs/tls.crt"
      KeyFile: "/etc/interlink/certs/tls.key"
      CACertFile: "/etc/interlink/certs/ca.crt"
`,
		namespace, namespace, caCertB64, caKeyB64, namespace, serverCertB64, serverKeyB64, caCertB64,
		namespace, clientCertB64, clientKeyB64, caCertB64, namespace)

	return manifest
}

// GenerateMTLSInstallScript creates an installation script for mTLS deployment
func GenerateMTLSInstallScript(config *InterLinkConfig, certs *CertificateBundle) string {
	script := `#!/bin/bash

# interLink mTLS Installation Script
# Generated by interLink WebUI

set -e

echo "🔐 Installing interLink with mTLS authentication..."

# Configuration
NAMESPACE="` + config.Namespace + `"
NODE_NAME="` + config.VKName + `"
INTERLINK_IP="` + config.InterLinkIP + `"
INTERLINK_PORT="` + fmt.Sprintf("%d", config.InterLinkPort) + `"

# Create certificates directory
mkdir -p ./interlink-certs
cd ./interlink-certs

echo "📜 Writing certificate files..."

# Write CA certificate
cat > ca.crt << 'EOF'
` + certs.CACert + `EOF

# Write CA private key
cat > ca.key << 'EOF'
` + certs.CAKey + `EOF

# Write server certificate
cat > server.crt << 'EOF'
` + certs.ServerCert + `EOF

# Write server private key
cat > server.key << 'EOF'
` + certs.ServerKey + `EOF

# Write client certificate
cat > client.crt << 'EOF'
` + certs.ClientCert + `EOF

# Write client private key
cat > client.key << 'EOF'
` + certs.ClientKey + `EOF

echo "🔒 Setting secure permissions on certificate files..."
chmod 600 *.key
chmod 644 *.crt

echo "☸️  Creating Kubernetes secrets..."

# Create namespace
kubectl create namespace $NAMESPACE --dry-run=client -o yaml | kubectl apply -f -

# Create CA secret
kubectl create secret generic interlink-ca-certs \
  --from-file=ca.crt=ca.crt \
  --from-file=ca.key=ca.key \
  -n $NAMESPACE \
  --dry-run=client -o yaml | kubectl apply -f -

# Create server certificate secret
kubectl create secret tls interlink-server-certs \
  --cert=server.crt \
  --key=server.key \
  -n $NAMESPACE \
  --dry-run=client -o yaml | kubectl apply -f -

# Add CA cert to server secret
kubectl patch secret interlink-server-certs -n $NAMESPACE \
  --patch="$(kubectl get secret interlink-ca-certs -n $NAMESPACE -o jsonpath='{.data.ca\.crt}' | \
            sed 's/.*/{"data":{"ca.crt":"&"}}/')"

# Create client certificate secret for Virtual Kubelet
kubectl create secret tls $NODE_NAME-tls-certs \
  --cert=client.crt \
  --key=client.key \
  -n $NAMESPACE \
  --dry-run=client -o yaml | kubectl apply -f -

# Add CA cert to client secret
kubectl patch secret $NODE_NAME-tls-certs -n $NAMESPACE \
  --patch="$(kubectl get secret interlink-ca-certs -n $NAMESPACE -o jsonpath='{.data.ca\.crt}' | \
            sed 's/.*/{"data":{"ca.crt":"&"}}/')"

echo "📝 Creating interLink configuration..."

# Create interLink configuration
cat > InterLinkConfig.yaml << EOF
InterlinkAddress: https://0.0.0.0
InterlinkPort: "3000"
SidecarURL: http://plugin
SidecarPort: "4000"
VerboseLogging: true
ErrorsOnlyLogging: false
DataRootFolder: "/tmp/interlink"

# mTLS Configuration
TLS:
  Enabled: true
  CertFile: "/etc/interlink/certs/tls.crt"
  KeyFile: "/etc/interlink/certs/tls.key"
  CACertFile: "/etc/interlink/certs/ca.crt"
EOF

kubectl create configmap interlink-config \
  --from-file=InterLinkConfig.yaml=InterLinkConfig.yaml \
  -n $NAMESPACE \
  --dry-run=client -o yaml | kubectl apply -f -

echo "🚀 Deploying with Helm..."

# Create Helm values file for mTLS
cat > mtls-values.yaml << EOF
nodeName: "$NODE_NAME"

virtualNode:
  resources:
    CPUs: ` + config.VKLimits.CPU + `
    memGiB: ` + config.VKLimits.Memory + `
    pods: ` + config.VKLimits.Pods + `
  HTTPProxies:
    HTTP: null
    HTTPs: null
  HTTP:
    insecure: false
    CACert: "/etc/vk/certs/ca.crt"
  kubeletHTTP:
    insecure: false
  tracing:
    enabled: false

interlink:
  enabled: false
  address: https://$INTERLINK_IP
  port: $INTERLINK_PORT
  tls:
    enabled: true
    certFile: "/etc/vk/certs/tls.crt"
    keyFile: "/etc/vk/certs/tls.key"
    caCertFile: "/etc/vk/certs/ca.crt"
EOF

# Deploy with Helm
helm upgrade --install \
  --create-namespace \
  -n $NAMESPACE \
  $NODE_NAME \
  oci://ghcr.io/interlink-project/interlink-helm-chart/interlink \
  --values mtls-values.yaml

echo "✅ mTLS deployment completed!"
echo ""
echo "📋 Next steps:"
echo "1. Copy server certificates to your edge node:"
echo "   scp server.crt server.key ca.crt user@$INTERLINK_IP:~/.interlink/certs/"
echo ""
echo "2. Update interLink configuration on edge node:"
echo "   scp InterLinkConfig.yaml user@$INTERLINK_IP:~/.interlink/config/"
echo ""
echo "3. Restart interLink service on edge node"
echo ""
echo "🔍 Test the deployment:"
echo "   kubectl get pods -n $NAMESPACE"
echo "   kubectl logs -n $NAMESPACE deployment/virtual-kubelet-$NODE_NAME"
echo ""
echo "🔐 Test mTLS connection:"
echo "   curl -v --cacert ca.crt --cert client.crt --key client.key https://$INTERLINK_IP:$INTERLINK_PORT/pinglink"

cd ..
`

	return script
}

// GenerateTunneledMTLSInstallScript creates an installation script for tunneled deployment with mTLS
func GenerateTunneledMTLSInstallScript(config *InterLinkConfig, certs *CertificateBundle) string {
	script := `#!/bin/bash

# interLink Tunneled + mTLS Installation Script
# Generated by interLink WebUI

set -e

echo "🚇 Installing interLink with Tunneled + mTLS deployment..."

# Configuration
NAMESPACE="` + config.Namespace + `"
NODE_NAME="` + config.VKName + `"
REMOTE_HOST="` + config.SSHTunnel.RemoteHost + `"
REMOTE_USER="` + config.SSHTunnel.RemoteUser + `"
SSH_PORT="` + fmt.Sprintf("%d", config.SSHTunnel.SSHPort) + `"
PLUGIN_PORT="` + fmt.Sprintf("%d", config.SSHTunnel.PluginPort) + `"
LOCAL_SOCKET="` + config.SSHTunnel.LocalSocket + `"
SSH_KEY_PATH="` + config.SSHTunnel.PrivateKeyPath + `"
HOST_KEY_PATH="` + config.SSHTunnel.HostKeyPath + `"

echo "📋 Deployment Configuration:"
echo "  Mode: Tunneled + mTLS"
echo "  Namespace: $NAMESPACE"
echo "  Node Name: $NODE_NAME"
echo "  Remote Host: $REMOTE_HOST:$SSH_PORT"
echo "  Remote User: $REMOTE_USER"
echo "  Plugin Port: $PLUGIN_PORT"
echo "  Local Socket: $LOCAL_SOCKET"

# Create system directories
sudo mkdir -p /opt/interlink/{bin,config,logs,.ssh,certs}
sudo useradd --system --create-home --home-dir /opt/interlink --shell /bin/bash interlink 2>/dev/null || true

echo "📜 Writing certificate files..."

# Write SSH keys
sudo tee /opt/interlink/.ssh/id_rsa > /dev/null << 'EOF'
` + config.SSHTunnel.SSHKeys.PrivateKey + `EOF

sudo tee /opt/interlink/.ssh/id_rsa.pub > /dev/null << 'EOF'
` + config.SSHTunnel.SSHKeys.PublicKeyOpenSSH + `EOF

# Write certificates to system directory
sudo tee /opt/interlink/certs/ca.crt > /dev/null << 'EOF'
` + certs.CACert + `EOF

sudo tee /opt/interlink/certs/server.crt > /dev/null << 'EOF'
` + certs.ServerCert + `EOF

sudo tee /opt/interlink/certs/server.key > /dev/null << 'EOF'
` + certs.ServerKey + `EOF

sudo tee /opt/interlink/certs/client.crt > /dev/null << 'EOF'
` + certs.ClientCert + `EOF

sudo tee /opt/interlink/certs/client.key > /dev/null << 'EOF'
` + certs.ClientKey + `EOF

echo "🔒 Setting secure permissions on SSH keys and certificate files..."
sudo chmod 600 /opt/interlink/.ssh/id_rsa /opt/interlink/certs/*.key
sudo chmod 644 /opt/interlink/.ssh/id_rsa.pub /opt/interlink/certs/*.crt
sudo chown -R interlink:interlink /opt/interlink

echo "📝 Creating tunneled + mTLS configuration files..."

# Create interLink configuration for tunneled deployment
sudo tee /opt/interlink/config/InterLinkConfig.yaml > /dev/null << EOF
# Tunneled deployment - listen on Unix socket
InterlinkAddress: unix://$LOCAL_SOCKET
InterlinkPort: ""

# Remote plugin configuration via SSH tunnel
SidecarURL: http://127.0.0.1
SidecarPort: "$PLUGIN_PORT"

VerboseLogging: true
ErrorsOnlyLogging: false
DataRootFolder: "/tmp/interlink"

# mTLS Configuration
TLS:
  Enabled: true
  CertFile: "/opt/interlink/certs/server.crt"
  KeyFile: "/opt/interlink/certs/server.key"
  CACertFile: "/opt/interlink/certs/ca.crt"
EOF

# Create Virtual Kubelet configuration for tunneled deployment
sudo tee /opt/interlink/config/VirtualKubeletConfig.yaml > /dev/null << EOF
# Connect to Unix socket
InterlinkURL: unix://$LOCAL_SOCKET
InterlinkPort: ""

VerboseLogging: true
ErrorsOnlyLogging: false

# Node configuration
NodeName: "$NODE_NAME"
NodeLabels:
  "interlink.cern.ch/provider": "tunneled-mtls"
  "interlink.cern.ch/deployment": "tunneled"
  "interlink.cern.ch/auth": "mtls"
EOF

echo "🚇 Creating SSH tunnel systemd service..."

# SSH Tunnel Service
sudo tee /etc/systemd/system/interlink-tunnel.service > /dev/null << EOF
[Unit]
Description=interLink SSH Tunnel (mTLS)
After=network.target
Wants=network.target

[Service]
Type=simple
User=interlink
Group=interlink
WorkingDirectory=/opt/interlink
ExecStart=/opt/interlink/bin/ssh-tunnel \\
  -addr "$REMOTE_HOST:$SSH_PORT" \\
  -user "$REMOTE_USER" \\
  -keyfile "$SSH_KEY_PATH" \\
  -lsock "$LOCAL_SOCKET" \\
  -rport "$PLUGIN_PORT"` +
		func() string {
			if config.SSHTunnel.HostKeyPath != "" {
				return ` \\
  -hostkeyfile "$HOST_KEY_PATH"`
			}
			return ""
		}() + `

Restart=always
RestartSec=10
StandardOutput=append:/opt/interlink/logs/ssh-tunnel.log
StandardError=append:/opt/interlink/logs/ssh-tunnel.log

# Security settings
NoNewPrivileges=true
ProtectSystem=strict
ProtectHome=true
ReadWritePaths=/opt/interlink/logs /tmp
PrivateTmp=true

[Install]
WantedBy=multi-user.target
EOF

echo "🔗 Creating interLink API systemd service..."

# interLink API Service
sudo tee /etc/systemd/system/interlink-api.service > /dev/null << EOF
[Unit]
Description=interLink API Server (Tunneled + mTLS)
After=network.target interlink-tunnel.service
Wants=network.target
Requires=interlink-tunnel.service

[Service]
Type=simple
User=interlink
Group=interlink
WorkingDirectory=/opt/interlink
Environment=INTERLINKCONFIGPATH=/opt/interlink/config/InterLinkConfig.yaml
ExecStart=/opt/interlink/bin/interlink
ExecReload=/bin/kill -HUP \$MAINPID
Restart=always
RestartSec=10
StandardOutput=append:/opt/interlink/logs/interlink-api.log
StandardError=append:/opt/interlink/logs/interlink-api.log

# Security settings
NoNewPrivileges=true
ProtectSystem=strict
ProtectHome=true
ReadWritePaths=/opt/interlink/logs /tmp
PrivateTmp=true

[Install]
WantedBy=multi-user.target
EOF

echo "☸️  Creating Kubernetes secrets..."

# Create namespace
kubectl create namespace $NAMESPACE --dry-run=client -o yaml | kubectl apply -f -

# Create certificates secrets for Kubernetes deployment
kubectl create secret tls $NODE_NAME-tls-certs \\
  --cert=/opt/interlink/certs/client.crt \\
  --key=/opt/interlink/certs/client.key \\
  -n $NAMESPACE \\
  --dry-run=client -o yaml | kubectl apply -f -

# Add CA cert to client secret
kubectl patch secret $NODE_NAME-tls-certs -n $NAMESPACE \\
  --patch="{\"data\":{\"ca.crt\":\"$(base64 -w 0 /opt/interlink/certs/ca.crt)\"}}"

echo "🚀 Creating Helm values for tunneled + mTLS deployment..."

# Create Helm values file for tunneled + mTLS
cat > /opt/interlink/tunneled-mtls-values.yaml << EOF
nodeName: "$NODE_NAME"

virtualNode:
  resources:
    CPUs: ` + config.VKLimits.CPU + `
    memGiB: ` + config.VKLimits.Memory + `
    pods: ` + config.VKLimits.Pods + `
  HTTPProxies:
    HTTP: null
    HTTPs: null
  HTTP:
    insecure: false
    CACert: "/etc/vk/certs/ca.crt"
  kubeletHTTP:
    insecure: false
  tracing:
    enabled: false

interlink:
  enabled: false
  address: unix://$LOCAL_SOCKET
  port: ""
  tls:
    enabled: true
    certFile: "/etc/vk/certs/tls.crt"
    keyFile: "/etc/vk/certs/tls.key"
    caCertFile: "/etc/vk/certs/ca.crt"

OAUTH:
  enabled: false
EOF

echo "📦 Installing required binaries..."
echo "Please ensure you have the following binaries in /opt/interlink/bin/:"
echo "  - ssh-tunnel"
echo "  - interlink"
echo "  - virtual-kubelet"
echo ""
echo "Download from: https://github.com/interlink-project/interlink/releases/"

echo "🔑 SSH keys have been automatically generated and are ready for use!"
echo ""
echo "📋 IMPORTANT: Install the public SSH key on the remote host:"
echo "   Remote host: $REMOTE_HOST"
echo "   Remote user: $REMOTE_USER"
echo ""
echo "Run this command on the remote host to install the public key:"
echo "   mkdir -p ~/.ssh && echo '` + strings.TrimSpace(config.SSHTunnel.SSHKeys.PublicKeyOpenSSH) + `' >> ~/.ssh/authorized_keys"
echo "   chmod 700 ~/.ssh && chmod 600 ~/.ssh/authorized_keys"
echo ""
echo "Or copy-paste this public key into the remote server's authorized_keys file:"
echo "-----BEGIN SSH PUBLIC KEY-----"
echo "` + strings.TrimSpace(config.SSHTunnel.SSHKeys.PublicKeyOpenSSH) + `"
echo "-----END SSH PUBLIC KEY-----"
echo ""

echo "🎯 Deploy with Helm..."
echo "helm upgrade --install \\"
echo "  --create-namespace \\"
echo "  -n $NAMESPACE \\"
echo "  $NODE_NAME \\"
echo "  oci://ghcr.io/interlink-project/interlink-helm-chart/interlink \\"
echo "  --values /opt/interlink/tunneled-mtls-values.yaml"

echo ""
echo "🚀 Enable and start services..."
echo "sudo systemctl daemon-reload"
echo "sudo systemctl enable interlink-tunnel interlink-api"
echo "sudo systemctl start interlink-tunnel"
echo "sudo systemctl start interlink-api"

echo ""
echo "✅ Tunneled + mTLS deployment script completed!"
echo ""
echo "📋 Next steps:"
echo "1. Install binaries in /opt/interlink/bin/"
echo "2. Set up SSH keys and connectivity to $REMOTE_HOST"
echo "3. Start the remote plugin on $REMOTE_HOST:$PLUGIN_PORT"
echo "4. Run the systemctl commands above"
echo "5. Deploy Virtual Kubelet with Helm"
echo ""
echo "🔍 Monitor deployment:"
echo "  sudo journalctl -f -u interlink-tunnel"
echo "  sudo journalctl -f -u interlink-api"
echo "  kubectl get nodes"
echo ""
echo "🔐 Test mTLS + Tunnel connection:"
echo "  curl --unix-socket $LOCAL_SOCKET http://unix/pinglink"
`

	return script
}
