package main

import (
	"context"
	"crypto/rand"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"html/template"
	"log"
	"net/http"
	"os"
	"strconv"
	"strings"
	"time"

	"github.com/gorilla/mux"
	"golang.org/x/oauth2"
	"gopkg.in/yaml.v3"
)

type Config struct {
	Server struct {
		Port int    `yaml:"port"`
		Host string `yaml:"host"`
	} `yaml:"server"`
	OIDC struct {
		ClientID     string   `yaml:"client_id"`
		ClientSecret string   `yaml:"client_secret"`
		RedirectURL  string   `yaml:"redirect_url"`
		Issuer       string   `yaml:"issuer"`
		Scopes       []string `yaml:"scopes"`
	} `yaml:"oidc"`
	TestMode bool `yaml:"test_mode"`
}

type InterLinkConfig struct {
	VKName           string            `yaml:"kubelet_node_name"`
	Namespace        string            `yaml:"kubernetes_namespace"`
	InterLinkIP      string            `yaml:"interlink_ip"`
	InterLinkPort    int               `yaml:"interlink_port"`
	InterLinkVersion string            `yaml:"interlink_version"`
	VKLimits         Resources         `yaml:"node_limits"`
	OAUTH            OAuthStruct       `yaml:"oauth"`
	HTTPInsecure     bool              `yaml:"insecure_http"`
	CACert           string            `yaml:"ca_cert,omitempty"`
	DisableProjected bool              `yaml:"disable_projected_volumes"`
	NodeLabels       map[string]string `yaml:"node_labels,omitempty"`
	NodeTaints       []NodeTaint       `yaml:"node_taints,omitempty"`
}

type Resources struct {
	CPU    string `yaml:"cpu"`
	Memory string `yaml:"memory"`
	Pods   string `yaml:"pods"`
}

type OAuthStruct struct {
	Provider      string   `yaml:"provider"`
	GrantType     string   `yaml:"grant_type"`
	Issuer        string   `yaml:"issuer,omitempty"`
	RefreshToken  string   `yaml:"refresh_token,omitempty"`
	Audience      string   `yaml:"audience,omitempty"`
	Group         string   `yaml:"group,omitempty"`
	GroupClaim    string   `yaml:"group_claim"`
	Scopes        []string `yaml:"scopes"`
	GitHubUser    string   `yaml:"github_user,omitempty"`
	TokenURL      string   `yaml:"token_url"`
	DeviceCodeURL string   `yaml:"device_code_url,omitempty"`
	ClientID      string   `yaml:"client_id"`
	ClientSecret  string   `yaml:"client_secret"`
}

type NodeTaint struct {
	Key    string `yaml:"key"`
	Value  string `yaml:"value"`
	Effect string `yaml:"effect"`
}

type SessionData struct {
	UserInfo   map[string]interface{}
	Tokens     *oauth2.Token
	ConfigData InterLinkConfig
}

var (
	config         Config
	sessions       = make(map[string]*SessionData)
	oauth2Config   *oauth2.Config
	helmTemplate   *template.Template
	scriptTemplate *template.Template
)

const helmValuesTemplate = `nodeName: {{.VKName}}

interlink:
  address: https://{{.InterLinkIP}}
  port: {{.InterLinkPort}}
  disableProjectedVolumes: {{.DisableProjected}}

virtualNode:
  resources:
    CPUs: {{.VKLimits.CPU}}
    memGiB: {{.VKLimits.Memory}}
    pods: {{.VKLimits.Pods}}
  HTTPProxies:
    HTTP: null
    HTTPs: null
  HTTP:
    CACert: {{ .CACert }}
    Insecure: {{.HTTPInsecure}}
{{- if .NodeLabels}}
  nodeLabels:
{{- range $key, $value := .NodeLabels}}
    - "{{$key}}={{$value}}"
{{- end}}
{{- end}}
{{- if .NodeTaints}}
  nodeTaints:
{{- range .NodeTaints}}
    - key: "{{.Key}}"
      value: "{{.Value}}"
      effect: "{{.Effect}}"
{{- end}}
{{- end}}

OAUTH:
  enabled: {{if .OAUTH.ClientID}}true{{else}}false{{end}}
{{- if .OAUTH.ClientID}}
  TokenURL: {{.OAUTH.TokenURL}}
  ClientID: {{.OAUTH.ClientID}}
  ClientSecret: {{.OAUTH.ClientSecret}}
  RefreshToken: {{.OAUTH.RefreshToken}}
  GrantType: {{.OAUTH.GrantType}}
  Audience: {{.OAUTH.Audience}}
{{- end}}
`

const installScriptTemplate = `#!/bin/bash

# interLink Remote Installation Script
# Generated by interLink WebUI

set -e

INTERLINK_VERSION="{{.InterLinkVersion}}"
INTERLINK_PORT="{{.InterLinkPort}}"
INTERLINK_IP="{{.InterLinkIP}}"

install() {
    echo "Installing interLink API Server version $INTERLINK_VERSION..."
    
    # Download interLink binary
    curl -Lo interlink "https://github.com/interlink-hq/interlink/releases/download/v$INTERLINK_VERSION/interlink-linux-amd64"
    chmod +x interlink
    sudo mv interlink /usr/local/bin/
    
    # Create configuration directory
    sudo mkdir -p /etc/interlink
    
    # Create interLink configuration
    cat > /tmp/interLinkConfig.yaml << 'EOF'
InterlinkAddress: "0.0.0.0"
InterlinkPort: {{.InterLinkPort}}
SidecarURL: "http://localhost:4000"
SidecarEndpoint: "http://localhost:4000"
VerboseLogging: true
ErrorsOnlyLogging: false
ExportPodData: true
DataRootFolder: "/tmp/interlink"
{{- if .OAUTH.ClientID}}
Oauth:
  Provider: "{{.OAUTH.Provider}}"
  Issuer: "{{.OAUTH.Issuer}}"
  Audience: "{{.OAUTH.Audience}}"
  ClientId: "{{.OAUTH.ClientID}}"
  ClientSecret: "{{.OAUTH.ClientSecret}}"
  GroupClaim: "{{.OAUTH.GroupClaim}}"
  {{- if .OAUTH.Group}}
  Group: "{{.OAUTH.Group}}"
  {{- end}}
{{- end}}
EOF
    
    sudo mv /tmp/interLinkConfig.yaml /etc/interlink/
    
    # Create systemd service
    cat > /tmp/interlink.service << 'EOF'
[Unit]
Description=interLink API Server
After=network.target

[Service]
Type=simple
User=root
ExecStart=/usr/local/bin/interlink --config /etc/interlink/interLinkConfig.yaml
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
EOF
    
    sudo mv /tmp/interlink.service /etc/systemd/system/
    sudo systemctl daemon-reload
    sudo systemctl enable interlink
    
    echo "interLink installed successfully!"
}

start() {
    echo "Starting interLink service..."
    sudo systemctl start interlink
    echo "interLink service started!"
    echo "Service status:"
    sudo systemctl status interlink --no-pager
}

stop() {
    echo "Stopping interLink service..."
    sudo systemctl stop interlink
    echo "interLink service stopped!"
}

case "$1" in
    install)
        install
        ;;
    start)
        start
        ;;
    stop)
        stop
        ;;
    *)
        echo "Usage: $0 {install|start|stop}"
        exit 1
        ;;
esac
`

func loadConfig() error {
	configFile := os.Getenv("WEBUI_CONFIG")
	if configFile == "" {
		configFile = "webui-config.yaml"
	}

	data, err := os.ReadFile(configFile)
	if err != nil {
		return fmt.Errorf("failed to read config file: %w", err)
	}

	if err := yaml.Unmarshal(data, &config); err != nil {
		return fmt.Errorf("failed to parse config file: %w", err)
	}

	return nil
}

func initTemplates() error {
	var err error
	helmTemplate, err = template.New("helm").Parse(helmValuesTemplate)
	if err != nil {
		return fmt.Errorf("failed to parse helm template: %w", err)
	}

	scriptTemplate, err = template.New("script").Parse(installScriptTemplate)
	if err != nil {
		return fmt.Errorf("failed to parse script template: %w", err)
	}

	return nil
}

func generateState() string {
	b := make([]byte, 32)
	if _, err := rand.Read(b); err != nil {
		log.Printf("Failed to generate random state: %v", err)
		return ""
	}
	return base64.URLEncoding.EncodeToString(b)
}

func main() {
	if err := loadConfig(); err != nil {
		log.Fatalf("Failed to load configuration: %v", err)
	}

	if err := initTemplates(); err != nil {
		log.Fatalf("Failed to initialize templates: %v", err)
	}

	oauth2Config = &oauth2.Config{
		ClientID:     config.OIDC.ClientID,
		ClientSecret: config.OIDC.ClientSecret,
		RedirectURL:  config.OIDC.RedirectURL,
		Scopes:       config.OIDC.Scopes,
		Endpoint: oauth2.Endpoint{
			AuthURL:  config.OIDC.Issuer + "/auth",
			TokenURL: config.OIDC.Issuer + "/token",
		},
	}

	r := mux.NewRouter()

	// Static file serving
	r.PathPrefix("/static/").Handler(http.StripPrefix("/static/", http.FileServer(http.Dir("./static/"))))

	// Routes
	r.HandleFunc("/", homeHandler).Methods("GET")
	r.HandleFunc("/auth/login", loginHandler).Methods("GET")
	r.HandleFunc("/auth/callback", callbackHandler).Methods("GET")
	r.HandleFunc("/auth/logout", logoutHandler).Methods("GET")
	r.HandleFunc("/configure", configureHandler).Methods("GET", "POST")
	r.HandleFunc("/generate/helm", generateHelmHandler).Methods("POST")
	r.HandleFunc("/generate/script", generateScriptHandler).Methods("POST")

	// Test mode routes
	if config.TestMode {
		r.HandleFunc("/auth/test-login", testLoginHandler).Methods("GET")
	}

	addr := fmt.Sprintf("%s:%d", config.Server.Host, config.Server.Port)

	server := &http.Server{
		Addr:         addr,
		Handler:      r,
		ReadTimeout:  15 * time.Second,
		WriteTimeout: 15 * time.Second,
		IdleTimeout:  60 * time.Second,
	}

	log.Printf("Starting webui server on %s", addr)
	log.Fatal(server.ListenAndServe())
}

func homeHandler(w http.ResponseWriter, r *http.Request) {
	sessionID, err := r.Cookie("session_id")
	if err != nil || sessions[sessionID.Value] == nil {
		renderTemplate(w, "login", map[string]interface{}{
			"TestMode": config.TestMode,
		})
		return
	}

	session := sessions[sessionID.Value]
	templateData := map[string]interface{}{
		"UserInfo":   session.UserInfo,
		"ConfigData": session.ConfigData,
		"Tokens":     session.Tokens,
		"TestMode":   config.TestMode,
	}
	renderTemplate(w, "home", templateData)
}

func loginHandler(w http.ResponseWriter, r *http.Request) {
	if config.TestMode {
		http.Redirect(w, r, "/auth/test-login", http.StatusTemporaryRedirect)
		return
	}

	state := generateState()
	http.SetCookie(w, &http.Cookie{
		Name:     "oauth_state",
		Value:    state,
		MaxAge:   600,
		HttpOnly: true,
		Secure:   false,
	})

	url := oauth2Config.AuthCodeURL(state)
	http.Redirect(w, r, url, http.StatusTemporaryRedirect)
}

func testLoginHandler(w http.ResponseWriter, r *http.Request) {
	if !config.TestMode {
		http.Error(w, "Test mode not enabled", http.StatusForbidden)
		return
	}

	// Create a dummy session with test user info
	sessionID := generateState()
	sessions[sessionID] = &SessionData{
		UserInfo: map[string]interface{}{
			"name":  "Test User",
			"email": "test@example.com",
			"sub":   "test-user-123",
		},
		Tokens: nil, // No real tokens in test mode
		ConfigData: InterLinkConfig{
			VKName:           "test-vk-node",
			Namespace:        "interlink",
			InterLinkVersion: "0.5.1",
			VKLimits: Resources{
				CPU:    "10",
				Memory: "256",
				Pods:   "10",
			},
			HTTPInsecure:     true,
			DisableProjected: true,
		},
	}

	http.SetCookie(w, &http.Cookie{
		Name:     "session_id",
		Value:    sessionID,
		MaxAge:   3600,
		HttpOnly: true,
		Secure:   false,
	})

	http.Redirect(w, r, "/", http.StatusTemporaryRedirect)
}

func callbackHandler(w http.ResponseWriter, r *http.Request) {
	stateCookie, err := r.Cookie("oauth_state")
	if err != nil || stateCookie.Value != r.URL.Query().Get("state") {
		http.Error(w, "Invalid state parameter", http.StatusBadRequest)
		return
	}

	code := r.URL.Query().Get("code")
	token, err := oauth2Config.Exchange(context.Background(), code)
	if err != nil {
		http.Error(w, "Failed to exchange token", http.StatusInternalServerError)
		return
	}

	userInfo, err := getUserInfo(token)
	if err != nil {
		http.Error(w, "Failed to get user info", http.StatusInternalServerError)
		return
	}

	sessionID := generateState()
	sessions[sessionID] = &SessionData{
		UserInfo: userInfo,
		Tokens:   token,
		ConfigData: InterLinkConfig{
			VKName:           "my-vk-node",
			Namespace:        "interlink",
			InterLinkVersion: "0.5.1",
			VKLimits: Resources{
				CPU:    "10",
				Memory: "256",
				Pods:   "10",
			},
			HTTPInsecure:     true,
			DisableProjected: true,
		},
	}

	http.SetCookie(w, &http.Cookie{
		Name:     "session_id",
		Value:    sessionID,
		MaxAge:   3600,
		HttpOnly: true,
		Secure:   false,
	})

	http.Redirect(w, r, "/", http.StatusTemporaryRedirect)
}

func logoutHandler(w http.ResponseWriter, r *http.Request) {
	sessionID, err := r.Cookie("session_id")
	if err == nil {
		delete(sessions, sessionID.Value)
	}

	http.SetCookie(w, &http.Cookie{
		Name:     "session_id",
		Value:    "",
		MaxAge:   -1,
		HttpOnly: true,
		Secure:   false,
	})

	http.Redirect(w, r, "/", http.StatusTemporaryRedirect)
}

func configureHandler(w http.ResponseWriter, r *http.Request) {
	sessionID, err := r.Cookie("session_id")
	if err != nil || sessions[sessionID.Value] == nil {
		http.Redirect(w, r, "/auth/login", http.StatusTemporaryRedirect)
		return
	}

	session := sessions[sessionID.Value]

	if r.Method == "POST" {
		// Parse form data and update configuration
		if err := r.ParseForm(); err != nil {
			http.Error(w, "Failed to parse form", http.StatusBadRequest)
			return
		}

		configData := &session.ConfigData
		configData.VKName = r.FormValue("vk_name")
		configData.Namespace = r.FormValue("namespace")
		configData.InterLinkIP = r.FormValue("interlink_ip")
		if port, err := strconv.Atoi(r.FormValue("interlink_port")); err == nil {
			configData.InterLinkPort = port
		}
		configData.InterLinkVersion = r.FormValue("interlink_version")
		configData.VKLimits.CPU = r.FormValue("cpu_limit")
		configData.VKLimits.Memory = r.FormValue("memory_limit")
		configData.VKLimits.Pods = r.FormValue("pods_limit")
		configData.HTTPInsecure = r.FormValue("http_insecure") == "on"
		configData.DisableProjected = r.FormValue("disable_projected") == "on"
		configData.CACert = r.FormValue("ca_cert")

		// Parse node labels
		nodeLabels := make(map[string]string)
		labelKeys := r.Form["label_key"]
		labelValues := r.Form["label_value"]
		for i, key := range labelKeys {
			if key != "" && i < len(labelValues) && labelValues[i] != "" {
				nodeLabels[key] = labelValues[i]
			}
		}
		if len(nodeLabels) > 0 {
			configData.NodeLabels = nodeLabels
		}

		// Parse node taints
		var nodeTaints []NodeTaint
		taintKeys := r.Form["taint_key"]
		taintValues := r.Form["taint_value"]
		taintEffects := r.Form["taint_effect"]
		for i, key := range taintKeys {
			if key != "" && i < len(taintValues) && i < len(taintEffects) {
				nodeTaints = append(nodeTaints, NodeTaint{
					Key:    key,
					Value:  taintValues[i],
					Effect: taintEffects[i],
				})
			}
		}
		configData.NodeTaints = nodeTaints

		// OAuth configuration
		configData.OAUTH.Provider = r.FormValue("oauth_provider")
		configData.OAUTH.GrantType = r.FormValue("oauth_grant_type")
		configData.OAUTH.Issuer = r.FormValue("oauth_issuer")
		configData.OAUTH.Audience = r.FormValue("oauth_audience")
		configData.OAUTH.Group = r.FormValue("oauth_group")
		configData.OAUTH.GroupClaim = r.FormValue("oauth_group_claim")
		configData.OAUTH.ClientID = r.FormValue("oauth_client_id")
		configData.OAUTH.ClientSecret = r.FormValue("oauth_client_secret")
		configData.OAUTH.TokenURL = r.FormValue("oauth_token_url")
		configData.OAUTH.DeviceCodeURL = r.FormValue("oauth_device_code_url")

		scopes := strings.Split(r.FormValue("oauth_scopes"), ",")
		for i, scope := range scopes {
			scopes[i] = strings.TrimSpace(scope)
		}
		configData.OAUTH.Scopes = scopes

		w.Header().Set("HX-Trigger", "configUpdated")
		templateData := map[string]interface{}{
			"UserInfo":   session.UserInfo,
			"ConfigData": session.ConfigData,
			"Tokens":     session.Tokens,
			"TestMode":   config.TestMode,
		}
		renderTemplate(w, "configure", templateData)
		return
	}

	templateData := map[string]interface{}{
		"UserInfo":   session.UserInfo,
		"ConfigData": session.ConfigData,
		"Tokens":     session.Tokens,
		"TestMode":   config.TestMode,
	}
	renderTemplate(w, "configure", templateData)
}

func generateHelmHandler(w http.ResponseWriter, r *http.Request) {
	sessionID, err := r.Cookie("session_id")
	if err != nil || sessions[sessionID.Value] == nil {
		http.Error(w, "Unauthorized", http.StatusUnauthorized)
		return
	}

	session := sessions[sessionID.Value]

	w.Header().Set("Content-Type", "application/x-yaml")
	w.Header().Set("Content-Disposition", "attachment; filename=values.yaml")

	if err := helmTemplate.Execute(w, session.ConfigData); err != nil {
		http.Error(w, "Failed to generate helm values", http.StatusInternalServerError)
		return
	}
}

func generateScriptHandler(w http.ResponseWriter, r *http.Request) {
	sessionID, err := r.Cookie("session_id")
	if err != nil || sessions[sessionID.Value] == nil {
		http.Error(w, "Unauthorized", http.StatusUnauthorized)
		return
	}

	session := sessions[sessionID.Value]

	w.Header().Set("Content-Type", "application/x-sh")
	w.Header().Set("Content-Disposition", "attachment; filename=interlink-install.sh")

	if err := scriptTemplate.Execute(w, session.ConfigData); err != nil {
		http.Error(w, "Failed to generate install script", http.StatusInternalServerError)
		return
	}
}

func getUserInfo(token *oauth2.Token) (map[string]interface{}, error) {
	client := oauth2Config.Client(context.Background(), token)
	resp, err := client.Get(config.OIDC.Issuer + "/userinfo")
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	var userInfo map[string]interface{}
	if err := json.NewDecoder(resp.Body).Decode(&userInfo); err != nil {
		return nil, err
	}

	return userInfo, nil
}

func renderTemplate(w http.ResponseWriter, templateName string, data interface{}) {
	templates := map[string]string{
		"login": `<!DOCTYPE html>
<html>
<head>
    <title>interLink WebUI - Login</title>
    <script src="https://unpkg.com/htmx.org@1.9.10"></script>
    <style>
        body { font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px; }
        .container { text-align: center; margin-top: 100px; }
        .btn { background: #007bff; color: white; padding: 10px 20px; text-decoration: none; border-radius: 5px; display: inline-block; margin: 5px; }
        .btn:hover { background: #0056b3; }
        .btn-warning { background: #ffc107; color: #212529; }
        .btn-warning:hover { background: #e0a800; }
        .test-mode-info { background: #fff3cd; border: 1px solid #ffeaa7; border-radius: 5px; padding: 15px; margin: 20px 0; }
    </style>
</head>
<body>
    <div class="container">
        <h1>interLink WebUI</h1>
        <p>Please authenticate to continue</p>
        <a href="/auth/login" class="btn">Login with OIDC</a>
        {{if .TestMode}}
        <div class="test-mode-info">
            <h3>🧪 Test Mode Enabled</h3>
            <p>You can use dummy authentication for testing purposes</p>
            <a href="/auth/test-login" class="btn btn-warning">Test Login (No OIDC)</a>
        </div>
        {{end}}
    </div>
</body>
</html>`,
		"home": `<!DOCTYPE html>
<html>
<head>
    <title>interLink WebUI - Dashboard</title>
    <script src="https://unpkg.com/htmx.org@1.9.10"></script>
    <style>
        body { font-family: Arial, sans-serif; max-width: 1200px; margin: 0 auto; padding: 20px; }
        .header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 30px; }
        .user-info { background: #f8f9fa; padding: 15px; border-radius: 5px; margin-bottom: 20px; }
        .btn { background: #007bff; color: white; padding: 10px 20px; text-decoration: none; border-radius: 5px; border: none; cursor: pointer; }
        .btn:hover { background: #0056b3; }
        .btn-secondary { background: #6c757d; }
        .btn-secondary:hover { background: #545b62; }
        .card { background: white; border: 1px solid #ddd; border-radius: 5px; padding: 20px; margin-bottom: 20px; }
        .actions { display: flex; gap: 10px; margin-top: 20px; }
    </style>
</head>
<body>
    <div class="header">
        <h1>interLink WebUI Dashboard</h1>
        <div>
            {{if .TestMode}}<span style="background: #fff3cd; padding: 5px 10px; border-radius: 3px; margin-right: 10px;">🧪 Test Mode</span>{{end}}
            <a href="/auth/logout" class="btn btn-secondary">Logout</a>
        </div>
    </div>
    
    {{if .UserInfo}}
    <div class="user-info">
        <strong>Welcome, {{.UserInfo.name}}!</strong>
        <p>Email: {{.UserInfo.email}}</p>
    </div>
    {{end}}
    
    <div class="card">
        <h2>Configuration</h2>
        <p>Configure your interLink deployment settings and generate the necessary files.</p>
        <div class="actions">
            <a href="/configure" class="btn">Configure Deployment</a>
        </div>
    </div>
    
    <div class="card">
        <h2>Generate Files</h2>
        <p>Download the generated Helm values and installation script for your deployment.</p>
        <div class="actions">
            <button hx-post="/generate/helm" hx-trigger="click" class="btn">Download Helm Values</button>
            <button hx-post="/generate/script" hx-trigger="click" class="btn">Download Install Script</button>
        </div>
    </div>
</body>
</html>`,
		"configure": `<!DOCTYPE html>
<html>
<head>
    <title>interLink WebUI - Configure</title>
    <script src="https://unpkg.com/htmx.org@1.9.10"></script>
    <style>
        body { font-family: Arial, sans-serif; max-width: 1200px; margin: 0 auto; padding: 20px; }
        .header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 30px; }
        .form-group { margin-bottom: 15px; }
        .form-group label { display: block; margin-bottom: 5px; font-weight: bold; }
        .form-group input, .form-group select, .form-group textarea { width: 100%; padding: 8px; border: 1px solid #ddd; border-radius: 4px; }
        .form-group textarea { height: 100px; }
        .btn { background: #007bff; color: white; padding: 10px 20px; border: none; border-radius: 5px; cursor: pointer; }
        .btn:hover { background: #0056b3; }
        .btn-secondary { background: #6c757d; }
        .btn-secondary:hover { background: #545b62; }
        .section { background: white; border: 1px solid #ddd; border-radius: 5px; padding: 20px; margin-bottom: 20px; }
        .section h3 { margin-top: 0; color: #333; }
        .row { display: flex; gap: 20px; }
        .col { flex: 1; }
        .dynamic-list { border: 1px solid #ddd; padding: 15px; border-radius: 4px; margin-top: 10px; }
        .dynamic-item { display: flex; gap: 10px; margin-bottom: 10px; align-items: center; }
        .dynamic-item input { flex: 1; }
        .btn-small { padding: 5px 10px; font-size: 12px; }
        .btn-danger { background: #dc3545; }
        .btn-danger:hover { background: #c82333; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Configure Deployment</h1>
        <div>
            {{if .TestMode}}<span style="background: #fff3cd; padding: 5px 10px; border-radius: 3px; margin-right: 10px;">🧪 Test Mode</span>{{end}}
            <a href="/" class="btn btn-secondary">Back to Dashboard</a>
            <a href="/auth/logout" class="btn btn-secondary">Logout</a>
        </div>
    </div>
    
    <form hx-post="/configure" hx-trigger="submit" hx-target="body">
        <div class="section">
            <h3>Basic Configuration</h3>
            <div class="row">
                <div class="col">
                    <div class="form-group">
                        <label for="vk_name">Virtual Kubelet Node Name:</label>
                        <input type="text" id="vk_name" name="vk_name" value="{{.ConfigData.VKName}}" required>
                    </div>
                    <div class="form-group">
                        <label for="namespace">Kubernetes Namespace:</label>
                        <input type="text" id="namespace" name="namespace" value="{{.ConfigData.Namespace}}" required>
                    </div>
                    <div class="form-group">
                        <label for="interlink_version">interLink Version:</label>
                        <input type="text" id="interlink_version" name="interlink_version" value="{{.ConfigData.InterLinkVersion}}" required>
                    </div>
                </div>
                <div class="col">
                    <div class="form-group">
                        <label for="interlink_ip">interLink IP Address:</label>
                        <input type="text" id="interlink_ip" name="interlink_ip" value="{{.ConfigData.InterLinkIP}}" required>
                    </div>
                    <div class="form-group">
                        <label for="interlink_port">interLink Port:</label>
                        <input type="number" id="interlink_port" name="interlink_port" value="{{.ConfigData.InterLinkPort}}" required>
                    </div>
                </div>
            </div>
        </div>
        
        <div class="section">
            <h3>Resource Limits</h3>
            <div class="row">
                <div class="col">
                    <div class="form-group">
                        <label for="cpu_limit">CPU Cores:</label>
                        <input type="text" id="cpu_limit" name="cpu_limit" value="{{.ConfigData.VKLimits.CPU}}" required>
                    </div>
                </div>
                <div class="col">
                    <div class="form-group">
                        <label for="memory_limit">Memory (GiB):</label>
                        <input type="text" id="memory_limit" name="memory_limit" value="{{.ConfigData.VKLimits.Memory}}" required>
                    </div>
                </div>
                <div class="col">
                    <div class="form-group">
                        <label for="pods_limit">Max Pods:</label>
                        <input type="text" id="pods_limit" name="pods_limit" value="{{.ConfigData.VKLimits.Pods}}" required>
                    </div>
                </div>
            </div>
        </div>
        
        <div class="section">
            <h3>HTTP/TLS Configuration</h3>
            <div class="row">
                <div class="col">
                    <div class="form-group">
                        <label>
                            <input type="checkbox" name="http_insecure" {{if .ConfigData.HTTPInsecure}}checked{{end}}> Allow Insecure HTTP
                        </label>
                    </div>
                    <div class="form-group">
                        <label>
                            <input type="checkbox" name="disable_projected" {{if .ConfigData.DisableProjected}}checked{{end}}> Disable Projected Volumes
                        </label>
                    </div>
                </div>
                <div class="col">
                    <div class="form-group">
                        <label for="ca_cert">CA Certificate (optional):</label>
                        <textarea id="ca_cert" name="ca_cert" placeholder="-----BEGIN CERTIFICATE-----">{{.ConfigData.CACert}}</textarea>
                    </div>
                </div>
            </div>
        </div>
        
        <div class="section">
            <h3>Node Labels</h3>
            <div id="node-labels">
                {{range $key, $value := .ConfigData.NodeLabels}}
                <div class="dynamic-item">
                    <input type="text" name="label_key" value="{{$key}}" placeholder="Key">
                    <input type="text" name="label_value" value="{{$value}}" placeholder="Value">
                    <button type="button" class="btn btn-danger btn-small" onclick="this.parentElement.remove()">Remove</button>
                </div>
                {{end}}
            </div>
            <button type="button" class="btn btn-secondary" onclick="addNodeLabel()">Add Label</button>
        </div>
        
        <div class="section">
            <h3>Node Taints</h3>
            <div id="node-taints">
                {{range .ConfigData.NodeTaints}}
                <div class="dynamic-item">
                    <input type="text" name="taint_key" value="{{.Key}}" placeholder="Key">
                    <input type="text" name="taint_value" value="{{.Value}}" placeholder="Value">
                    <select name="taint_effect">
                        <option value="NoSchedule" {{if eq .Effect "NoSchedule"}}selected{{end}}>NoSchedule</option>
                        <option value="PreferNoSchedule" {{if eq .Effect "PreferNoSchedule"}}selected{{end}}>PreferNoSchedule</option>
                        <option value="NoExecute" {{if eq .Effect "NoExecute"}}selected{{end}}>NoExecute</option>
                    </select>
                    <button type="button" class="btn btn-danger btn-small" onclick="this.parentElement.remove()">Remove</button>
                </div>
                {{end}}
            </div>
            <button type="button" class="btn btn-secondary" onclick="addNodeTaint()">Add Taint</button>
        </div>
        
        <div class="section">
            <h3>OAuth Configuration</h3>
            <div class="row">
                <div class="col">
                    <div class="form-group">
                        <label for="oauth_provider">Provider:</label>
                        <select id="oauth_provider" name="oauth_provider">
                            <option value="">None</option>
                            <option value="oidc" {{if eq .ConfigData.OAUTH.Provider "oidc"}}selected{{end}}>OIDC</option>
                            <option value="github" {{if eq .ConfigData.OAUTH.Provider "github"}}selected{{end}}>GitHub</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="oauth_grant_type">Grant Type:</label>
                        <select id="oauth_grant_type" name="oauth_grant_type">
                            <option value="authorization_code" {{if eq .ConfigData.OAUTH.GrantType "authorization_code"}}selected{{end}}>Authorization Code</option>
                            <option value="client_credentials" {{if eq .ConfigData.OAUTH.GrantType "client_credentials"}}selected{{end}}>Client Credentials</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="oauth_client_id">Client ID:</label>
                        <input type="text" id="oauth_client_id" name="oauth_client_id" value="{{.ConfigData.OAUTH.ClientID}}">
                    </div>
                    <div class="form-group">
                        <label for="oauth_client_secret">Client Secret:</label>
                        <input type="password" id="oauth_client_secret" name="oauth_client_secret" value="{{.ConfigData.OAUTH.ClientSecret}}">
                    </div>
                </div>
                <div class="col">
                    <div class="form-group">
                        <label for="oauth_issuer">Issuer URL:</label>
                        <input type="url" id="oauth_issuer" name="oauth_issuer" value="{{.ConfigData.OAUTH.Issuer}}">
                    </div>
                    <div class="form-group">
                        <label for="oauth_token_url">Token URL:</label>
                        <input type="url" id="oauth_token_url" name="oauth_token_url" value="{{.ConfigData.OAUTH.TokenURL}}">
                    </div>
                    <div class="form-group">
                        <label for="oauth_device_code_url">Device Code URL:</label>
                        <input type="url" id="oauth_device_code_url" name="oauth_device_code_url" value="{{.ConfigData.OAUTH.DeviceCodeURL}}">
                    </div>
                    <div class="form-group">
                        <label for="oauth_audience">Audience:</label>
                        <input type="text" id="oauth_audience" name="oauth_audience" value="{{.ConfigData.OAUTH.Audience}}">
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <div class="form-group">
                        <label for="oauth_group">Required Group:</label>
                        <input type="text" id="oauth_group" name="oauth_group" value="{{.ConfigData.OAUTH.Group}}">
                    </div>
                </div>
                <div class="col">
                    <div class="form-group">
                        <label for="oauth_group_claim">Group Claim:</label>
                        <input type="text" id="oauth_group_claim" name="oauth_group_claim" value="{{.ConfigData.OAUTH.GroupClaim}}" placeholder="groups">
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label for="oauth_scopes">Scopes (comma-separated):</label>
                <input type="text" id="oauth_scopes" name="oauth_scopes" value="{{range $i, $scope := .ConfigData.OAUTH.Scopes}}{{if $i}}, {{end}}{{$scope}}{{end}}" placeholder="openid, email, profile">
            </div>
        </div>
        
        <div class="section">
            <button type="submit" class="btn">Save Configuration</button>
        </div>
    </form>
    
    <script>
        function addNodeLabel() {
            const container = document.getElementById('node-labels');
            const div = document.createElement('div');
            div.className = 'dynamic-item';
            div.innerHTML = '<input type="text" name="label_key" placeholder="Key">' +
                           '<input type="text" name="label_value" placeholder="Value">' +
                           '<button type="button" class="btn btn-danger btn-small" onclick="this.parentElement.remove()">Remove</button>';
            container.appendChild(div);
        }
        
        function addNodeTaint() {
            const container = document.getElementById('node-taints');
            const div = document.createElement('div');
            div.className = 'dynamic-item';
            div.innerHTML = '<input type="text" name="taint_key" placeholder="Key">' +
                           '<input type="text" name="taint_value" placeholder="Value">' +
                           '<select name="taint_effect">' +
                               '<option value="NoSchedule">NoSchedule</option>' +
                               '<option value="PreferNoSchedule">PreferNoSchedule</option>' +
                               '<option value="NoExecute">NoExecute</option>' +
                           '</select>' +
                           '<button type="button" class="btn btn-danger btn-small" onclick="this.parentElement.remove()">Remove</button>';
            container.appendChild(div);
        }
    </script>
</body>
</html>`,
	}

	tmpl := template.Must(template.New(templateName).Parse(templates[templateName]))
	if err := tmpl.Execute(w, data); err != nil {
		http.Error(w, "Template error", http.StatusInternalServerError)
		log.Printf("Template error: %v", err)
	}
}
