name: build-images

on:
  push:
    branches: [next]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Integration Test
        uses: dagger/dagger-for-github@v5
        with:
          workdir: ci
          verb: call
          args: test stdout
