name: integration-tests 

on:
  push:
    #branches: [main,next,next2next]
  pull_request:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run plugin
        run: |
          git clone https://github.com/interTwin-eu/interlink-slurm-plugin.git \
          && cd interlink-slurm-plugin/docker \
          && docker compose up -d 
      - name: Get Repo Owner
        id: get_repo_owner
        run: echo ::set-output name=repo_owner::$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')
      - name: Integration Test
        uses: dagger/dagger-for-github@v6
        with:
          workdir: ci
          verb: call
          args: -s --name slurm-test build-images new-interlink --plugin-endpoint tcp://localhost:4000 test stdout
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
          version: "0.13.0"
