name: integration-tests 

on:
  push:
    #branches: [main,next,next2next]
  pull_request:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run plugin
        run: |
          wget https://github.com/interTwin-eu/interlink-docker-plugin/releases/download/0.0.24-no-gpu/docker-plugin_Linux_x86_64 -O docker-plugin \
          && chmod +x docker-plugin \
          && docker ps \
          && export INTERLINKCONFIGPATH=$PWD/ci/manifests/plugin-config.yaml \
          && ./docker-plugin &
      - name: Get Repo Owner
        id: get_repo_owner
        run: echo ::set-output name=repo_owner::$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')
      - name: Integration Test
        uses: dagger/dagger-for-github@v6
        with:
          workdir: ci
          verb: call
          args: -s --name my-test build-images --source-folder ../ new-interlink --plugin-endpoint tcp://localhost:4000 --manifests ./manifests test stdout
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
          version: "0.13.0"
          #dagger-flags: -d
