name: integration-tests 

on:
  push:
    branches: [main,next]
  pull_request:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Integration Test
        uses: dagger/dagger-for-github@v5
        with:
          workdir: ci
          verb: call
          args: -s build-images --source-folder ../ --virtual-kubelet-ref ghcr.io/intertwin-eu/virtual-kubelet-inttw:test --interlink-ref ghcr.io/intertwin-eu/interlink:test  new-interlink --manifests $PWD/manifests load-plugin test stdout
          #dagger-flags: -d
