---
name: Lint

on:
  push:
  pull_request:

jobs:
  super-lint:
    name: Lint with Super-Linter
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Make sure the actual branch is checked out when running on PR
          # ref: ${{ github.event.pull_request.head.sha }}
          # Full git history needed to get proper list of changed files
          fetch-depth: 0

      # Runs the Super-Linter action
      - name: Run Super-Linter on new changes
        uses: super-linter/super-linter@v7.1.0 
        env:
          FILTER_REGEX_EXCLUDE: ci/.*,example/.*
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MARKDOWN_CONFIG_FILE: .markdownlint.json
          VALIDATE_CHECKOV: false
          VALIDATE_MARKDOWN_PRETTIER: false
          VALIDATE_CSS_PRETTIER: false
          VALIDATE_BASH: false
          VALIDATE_GITHUB_ACTIONS: false
          VALIDATE_MARKDOWN: false
          VALIDATE_PYTHON_BLACK: false
          VALIDATE_PYTHON_PYINK: false
          # Only check new or edited files
          VALIDATE_ALL_CODEBASE: true
          # Fail on errors
          DISABLE_ERRORS: false
